blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/orgs/githitech/discussions/
    about: Search questions and ideas.
  - name: Confidential Issues and Bugs
    url: "https://www.githi.io/confidential.htm"
    about: Submit any confidential bugs or issues to the GitHi team
  - name: Documentation
    url: https://docs.githi.io/
    about: Documentation for features, guides, best practices, known issues, troubleshooting, and more.
  - name: GitHi Homepage
    url: https://githi.io/
    about: GitHi website.
